### ISSUE TITLE
Keyboard:. Arrow keys

### ISSUE THREAD

**Issue by GJO59** [VCCE/VCC#60] opened 2020-12-16 01:52 UTC
As of 2.1.0b the emulator does not recognize the arrow keys in any of the 3 default choices.

**Comment by BGPierce** [comment] 2020-12-16 03:07
I'm currently running VCC 2.1.0b and have tested all keyboard modes in both OS-9 and RSDOS and have full arrow key use.
I cannot duplicate your error without further information.
Also, no other users have complained of this and I know OS9 users and gamers would have complained by now :-)

Do you have "Config/Joysticks/Keyboard" selected and the arrow keys defined for joysticks? if so, this disables them for normal use (as it does for any key mapped to the joysticks)

Also, if you're using OS-9, and have hit <CNTRL><CLEAR/(HOME)> then you have turned on OS9's "Mouse Key" function in which the arrow keys function as a mouse and disabled otherwise. If this is the case, hit <CNTRL><CLEAR/(HOME)> again to disable it.

If the two reasons above do not fit your situation, what program are you running that is using the arrow keys?

Bill P.

**Comment by GJO59** [comment] 2020-12-17 01:43
Thanks for the quick response.  I note that this behavior was not mentioned in the "Welcome to Vcc 201c.pdf" (which I read), but was mentioned in "Welcome to Vcc 210b.pdf" (which I did not), although the behavior occurs in both versions of the emulator.
The error was mine for not reading the fine manual.
- Greg -


    On Tuesday, December 15, 2020, 07:07:44 PM PST, Bill Pierce <notifications@github.com> wrote:  
 
 

I'm currently running VCC 2.1.0b and have tested all keyboard modes in both OS-9 and RSDOS and have full arrow key use.
I cannot duplicate your error without further information.
Also, no other users have complained of this and I know OS9 users and gamers would have complained by now :-)

Do you have "Config/Joysticks/Keyboard" selected and the arrow keys defined for joysticks? if so, this disables them for normal use (as it does for any key mapped to the joysticks)

Also, if you're using OS-9, and have hit <CNTRL><CLEAR/(HOME)> then you have turned on OS9's "Mouse Key" function in which the arrow keys function as a mouse and disabled otherwise. If this is the case, hit <CNTRL><CLEAR/(HOME)> again to disable it.

If the two reasons above do not fit your situation, what program are you running that is using the arrow keys?

Bill P.

**Comment by ejaquay** [comment] 2021-03-24 12:57
On some keyboards the arrow keys are bound to the numpad 4, 6, 8, and 2 keys, which Vcc then maps back to arrows.  This should be fixed on the Vcc next release and could possibly have been the cause of this particulal issue (depends on PC  hardware).  Also this issue could be use of keyboard mouse as Bill P suggested in previous comment.

**Comment by ejaquay** [comment] 2021-04-17 13:23
A fix for the mapping of numpad arrow keys has been merged.  This should resolve that issue with the next release.

**Closed as completed** 2022-11-14 23:40 UTC
